services:
  postgres:
    image: postgres:16
    container_name: forgedesk_postgres
    restart: always
    environment:
      POSTGRES_USER: forgedesk_user
      POSTGRES_PASSWORD: forgedesk_pass
      POSTGRES_DB: forgedesk_db
    ports:
      - "5432:5432"
    volumes:
      - forgedesk_pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: forgedesk_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: forgedesk
      RABBITMQ_DEFAULT_PASS: forgedesk
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  forgedesk_pgdata:
