services:
  postgres:
    image: postgres:16
    container_name: forgedesk_postgres
    restart: always
    environment:
      POSTGRES_USER: forgedesk_user
      POSTGRES_PASSWORD: forgedesk_pass
      POSTGRES_DB: forgedesk_db
    ports:
      - "5432:5432"
    volumes:
      - forgedesk_pgdata:/var/lib/postgresql/data

volumes:
  forgedesk_pgdata: